# Generated by Django 6.0 on 2025-12-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerprofile",
            name="pu_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="PU Code"
            ),
        ),
    ]
