# Generated by Django 6.0 on 2026-01-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trainerprofile_pu_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('pu_code', models.CharField(max_length=50)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pending User Registration',
                'verbose_name_plural': 'Pending User Registrations',
            },
        ),
    ]
