# Generated by Django 6.0 on 2026-01-02 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendinguserregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguserregistration',
            name='designation',
            field=models.CharField(default='WT', max_length=20),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='designation',
            field=models.CharField(choices=[('PM', 'PM'), ('PRC', 'PRC'), ('TS', 'TS'), ('GE', 'GE'), ('M&E', 'M&E'), ('PUM', 'PUM'), ('WT', 'WT'), ('IT', 'IT'), ('Finance', 'Finance'), ('Admin', 'Admin')], default='WT', max_length=20, verbose_name='Designation'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=10, verbose_name='Status')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Marked At')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Marked By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'user__first_name'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
