# Generated by Django 6.0 on 2025-12-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MileageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("start_km", models.PositiveIntegerField()),
                ("end_km", models.PositiveIntegerField()),
                ("start_photo", models.ImageField(upload_to="start/")),
                ("end_photo", models.ImageField(upload_to="end/")),
                ("distance", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("WARNING", "WARNING"),
                            ("ALERT", "ALERT"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("trainer", "date")},
            },
        ),
    ]
