# Generated by Django 6.0 on 2025-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mileagerecord",
            name="distance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mileagerecord",
            name="end_km",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mileagerecord",
            name="end_photo",
            field=models.ImageField(blank=True, null=True, upload_to="end/"),
        ),
        migrations.AlterField(
            model_name="mileagerecord",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("WARNING", "WARNING"), ("ALERT", "ALERT")],
                max_length=10,
                null=True,
            ),
        ),
    ]
