# Generated by Django 6.0 on 2025-12-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage", "0002_alter_mileagerecord_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mileagerecord",
            name="submission_status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mileagerecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
