# Generated by Django 6.0 on 2025-12-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage", "0003_mileagerecord_submission_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mileagerecord",
            name="edit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
